packages:
  - "packages/*"
  - "backend"
  - "web"
  - "e2e/*"
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  msgpackr-extract: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.11'
  - '@biomejs/cli-darwin-arm64@2.5.11'
  - '@biomejs/cli-darwin-x64@2.5.11'
  - '@biomejs/cli-linux-arm64-musl@2.5.11'
  - '@biomejs/cli-linux-arm64@2.5.11'
  - '@biomejs/cli-linux-x64-musl@2.5.11'
  - '@biomejs/cli-linux-x64@2.5.11'
  - '@biomejs/cli-win32-arm64@2.5.11'
  - '@biomejs/cli-win32-x64@2.5.11'
  - '@jest/console@30.5.0'
  - '@jest/core@30.5.0'
  - '@jest/diff-sequences@30.5.0'
  - '@jest/environment-jsdom-abstract@30.5.0'
  - '@jest/environment@30.5.0'
  - '@jest/expect-utils@30.5.0'
  - '@jest/expect@30.5.0'
  - '@jest/fake-timers@30.5.0'
  - '@jest/get-type@30.5.0'
  - '@jest/globals@30.5.0'
  - '@jest/pattern@30.5.0'
  - '@jest/reporters@30.5.0'
  - '@jest/schemas@30.5.0'
  - '@jest/snapshot-utils@30.5.0'
  - '@jest/source-map@30.5.0'
  - '@jest/test-result@30.5.0'
  - '@jest/test-sequencer@30.5.0'
  - '@jest/transform@30.5.0'
  - '@jest/types@30.5.0'
  - '@testing-library/react@16.3.3'
  - babel-jest@30.5.0
  - babel-plugin-jest-hoist@30.5.0
  - babel-preset-jest@30.5.0
  - expect@30.5.0
  - jest-changed-files@30.5.0
  - jest-circus@30.5.0
  - jest-cli@30.5.0
  - jest-config@30.5.0
  - jest-diff@30.5.0
  - jest-docblock@30.5.0
  - jest-each@30.5.0
  - jest-environment-jsdom@30.5.0
  - jest-environment-node@30.5.0
  - jest-haste-map@30.5.0
  - jest-leak-detector@30.5.0
  - jest-matcher-utils@30.5.0
  - jest-message-util@30.5.0
  - jest-mock@30.5.0
  - jest-regex-util@30.5.0
  - jest-resolve-dependencies@30.5.0
  - jest-resolve@30.5.0
  - jest-runner@30.5.0
  - jest-runtime@30.5.0
  - jest-snapshot@30.5.0
  - jest-util@30.5.0
  - jest-validate@30.5.0
  - jest-watcher@30.5.0
  - jest-worker@30.5.0
  - jest@30.5.0
  - pretty-format@30.5.0
  - '@effect/platform@0.97.2'
  - effect@3.22.2
  - '@effect/platform-node@0.108.2'
  - '@aws-sdk/client-sesv2@3.1128.0'
  - scheduler@0.28.0
